# Generated by Django 5.2.14 on 2026-05-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('emotions', '0003_userdevicetoken_reminderdispatchlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('purpose', models.CharField(choices=[('password_reset', 'Password Reset')], db_index=True, max_length=32)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('send_count', models.PositiveSmallIntegerField(default=1)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_phone_verification_code',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['phone', 'purpose', 'created_at'], name='acct_verify_phone_purp_idx'), models.Index(fields=['purpose', 'expires_at'], name='acct_verify_purp_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wechat', 'WeChat'), ('qq', 'QQ')], db_index=True, max_length=16)),
                ('open_id', models.CharField(max_length=128)),
                ('union_id', models.CharField(blank=True, max_length=128)),
                ('app_id', models.CharField(blank=True, max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='emotions.appuser')),
            ],
            options={
                'db_table': 'accounts_user_social_account',
                'ordering': ('provider', 'id'),
                'indexes': [models.Index(fields=['user', 'provider'], name='acct_soc_user_prov_idx'), models.Index(fields=['provider', 'union_id'], name='acct_soc_prov_union_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'open_id'), name='acct_soc_provider_oid_uq')],
            },
        ),
    ]
