# Generated by Django 5.2.14 on 2026-05-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='treeholepost',
            new_name='moderation__status_3522f2_idx',
            old_name='moderatio_status_6320f8_idx',
        ),
        migrations.RenameIndex(
            model_name='treeholepost',
            new_name='moderation__emotion_33f531_idx',
            old_name='moderatio_emotion_4e42fe_idx',
        ),
    ]
