# Generated by Django 5.2.14 on 2026-05-15 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_appuser_auth_and_privacy_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='android', max_length=16)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='emotions.appuser')),
            ],
            options={
                'db_table': 'emotions_user_device_token',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReminderDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_dispatch_logs', to='emotions.appuser')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='emotions.userdevicetoken')),
            ],
            options={
                'db_table': 'emotions_reminder_dispatch_log',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UserReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('reminder_time', models.TimeField(default='09:00')),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('frequency_per_day', models.PositiveSmallIntegerField(default=1)),
                ('preferred_content_types', models.JSONField(blank=True, default=list)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preference', to='emotions.appuser')),
            ],
            options={
                'db_table': 'emotions_user_reminder_preference',
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='EmotionDataExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='emotions.appuser')),
            ],
            options={
                'db_table': 'emotions_data_export_task',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'status'], name='emo_exp_user_status_idx'), models.Index(fields=['file_format', 'created_at'], name='emo_exp_format_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userdevicetoken',
            index=models.Index(fields=['user', 'is_active'], name='emo_dev_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicetoken',
            index=models.Index(fields=['platform', 'is_active'], name='emo_dev_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderdispatchlog',
            index=models.Index(fields=['user', 'status'], name='emo_rem_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderdispatchlog',
            index=models.Index(fields=['status', 'next_retry_at'], name='emo_rem_retry_idx'),
        ),
    ]
