# Generated by Django 5.2.14 on 2026-05-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companioncontent',
            new_name='content_com_content_afef57_idx',
            old_name='content_com_content_17cafe_idx',
        ),
        migrations.RenameIndex(
            model_name='companioncontent',
            new_name='content_com_is_acti_ae6647_idx',
            old_name='content_com_is_acti_40b74c_idx',
        ),
        migrations.RenameIndex(
            model_name='companioncontent',
            new_name='content_com_emotion_4f987f_idx',
            old_name='content_com_emotion_a9ce7b_idx',
        ),
        migrations.RenameIndex(
            model_name='systemconfig',
            new_name='content_sys_key_9d289a_idx',
            old_name='content_sys_key_2e8a16_idx',
        ),
    ]
